steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/botwiner-repo/botwiner-api:latest'
      - '-f'
      - 'Dockerfile.api'
      - '.'
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/botwiner-repo/botwiner-api:latest'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _REGION: europe-west3
